version: '3'

services:
  web:
    build: ./php
    volumes:
    - ./php/www:/var/www/site
    ports:
    - 5001:80
  web2:
    image: php:apache
    volumes:
      - ./php2:/var/www/html
    ports:
      - 5003:80
